Repository ESIPFed/esipDMP, pull requests merged in 2025-03, with the labels that each got.

#1 Update index.qmd - add ESIP link
  index.qmd
Labels: enhancement

#2 Gains issue templates.
  .Rprofile
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/non-trivial-revision-to-current-content.md
  .github/ISSUE_TEMPLATE/small-problem--e-g-typos-and-broken-links-.md
  .github/ISSUE_TEMPLATE/suggest-content.md
  renv.lock
  renv/.gitignore
  renv/activate.R
  renv/settings.json
Labels: enhancement

#4 Gains explicit URL for the ‘Report an Issue’ action.
  .github/ISSUE_TEMPLATE/config.yml
  _quarto.yml
Labels: bug, Normal Priority

#6 Gains `blank-issue` template.
  .github/ISSUE_TEMPLATE/blank-issue.md
Labels: bug, enhancement

#7 Gains `sections/` with initial scaffold for content.
  _quarto.yml
  sections/access.qmd
  sections/data_management.qmd
  sections/outputs.qmd
  sections/pids.qmd
  sections/roles_responsibilities.qmd
  sections/standardization.qmd
Labels: documentation, enhancement, Normal Priority
