Repository ESIPFed/esipDMP, pull requests merged in 2025-07, with the labels that each got.

#26 New text added to Welcome page.
  _quarto.yml
  index.qmd
Labels: bug, enhancement

#41 Common standard terms pids
  sections/outputs.qmd
  sections/roles_responsibilities.qmd
  sections/standardization.qmd
Labels: documentation, enhancement

#43 Handling sidebar behaviour.
  assets/styles/theme-dark.scss
  assets/styles/theme.scss
Labels: bug

#59 redirect author links to works cited page in new tab
  _quarto.yml
  sections/dmp_content/access.qmd
  sections/dmp_content/outputs.qmd
  sections/dmp_content/roles_responsibilities.qmd
  sections/dmp_content/standardization.qmd
Labels: enhancement

#61 DMP Common Standards links (Needs consistent hyperlink format)
  sections/dmp_content/access.qmd
  sections/dmp_content/outputs.qmd
  sections/dmp_content/roles_responsibilities.qmd
  sections/dmp_content/standardization.qmd
Labels: documentation, enhancement

#62 Added lifecyle explanation - Improved team ORCiDs
  _extensions/mcanouil/iconify/LICENSE
  _extensions/mcanouil/iconify/_extension.yml
  _extensions/mcanouil/iconify/iconify-icon.min.js
  _extensions/mcanouil/iconify/iconify.lua
  index.qmd
  sections/introduction/data_lifecycle.qmd
Labels: documentation, enhancement

#63 Update to Works cited section and missing link in Welcome page.
  index.qmd
  sections/references_resources/works_cited.qmd
Labels: documentation

#64 Removed Arnosti from works cited
  sections/references_resources/works_cited.qmd
Labels: bug, documentation
